import os

MONGO_DEFAULT_URL = os.getenv("MONGO_DEFAULT_URL")
MONGO_DATA_URL = os.getenv("MONGO_DATA_URL")
OPEN_AI_KEY = os.getenv("OPENAI_KEY")
DESCRIPTION_SIZE = 3000
USERNAME_OPENSEARCH = os.getenv("USERNAME_OPENSEARCH")
PASSWORD_OPENSEARCH = os.getenv("PASSWORD_OPENSEARCH")